services:
  - name: mongo:6
    alias: mongo

variables:
  MONGO_URI: mongodb://mongo:27017/testdb

stages:
  - install
  - test
  - build

# paczki
install_backend_dependencies:
  stage: install
  image: python:3.10
  script:
    - cd backend
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - backend/venv
    expire_in: 1h

install_frontend_dependencies:
  stage: install
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
    expire_in: 1h

# testy
test_unit_weather:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-weather.xml --junitxml=report-weather.xml tests/test_unit_weather.py
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage-weather.xml
      junit: backend/report-weather.xml

test_mocked_db:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-mocked.xml --junitxml=report-mocked.xml tests/test_mocked_db.py
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage-mocked.xml
      junit: backend/report-mocked.xml

test_integration_auth:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-auth.xml --junitxml=report-auth.xml tests/test_integration_auth.py
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage-auth.xml
      junit: backend/report-auth.xml

test_integration_activities:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-activities.xml --junitxml=report-activities.xml tests/test_integration_activities.py
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage-activities.xml
      junit: backend/report-activities.xml

# build
frontend_build:
  stage: build
  image: node:20
  dependencies:
    - install_frontend_dependencies
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist
