services:
  - name: mongo:6
    alias: mongo

variables:
  MONGO_URI: mongodb://mongo:27017/testdb

stages:
  - install
  - test
  - build

# paczki
install_backend_dependencies:
  stage: install
  image: python:3.10
  script:
    - cd backend
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt pytest-cov
  artifacts:
    paths:
      - backend/venv
    expire_in: 1h

install_frontend_dependencies:
  stage: install
  image: node:20
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
    expire_in: 1h

# testy
test_unit_weather:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-weather.xml tests/test_unit_weather.py
  artifacts:
    reports:
      cobertura: backend/coverage-weather.xml

test_mocked_db:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-mocked.xml tests/test_mocked_db.py
  artifacts:
    reports:
      cobertura: backend/coverage-mocked.xml

test_integration_auth:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-auth.xml tests/test_integration_auth.py
  artifacts:
    reports:
      cobertura: backend/coverage-auth.xml

test_integration_activities:
  stage: test
  image: python:3.10
  dependencies:
    - install_backend_dependencies
  script:
    - cd backend
    - source venv/bin/activate
    - pytest --cov=. --cov-report=xml:coverage-activities.xml tests/test_integration_activities.py
  artifacts:
    reports:
      cobertura: backend/coverage-activities.xml

# build
frontend_build:
  stage: build
  image: node:20
  dependencies:
    - install_frontend_dependencies
  script:
    - npm run build
  artifacts:
    paths:
      - frontend/dist
